name: Waka Readme

# on:
#   schedule:
#     - cron: "0 */2 * * *" # Runs every 2 hours
#   workflow_dispatch:
on:
  schedule:
    - cron: "0 8 * * *"  # Runs at 8 AM UTC
    - cron: "0 20 * * *" # Runs at 8 PM UTC
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_OS: "True"
          SHOW_PROJECTS: "True"
          SHOW_TOTAL_CODE_TIME: "True"
          SHOW_PROFILE_VIEWS: "True"
          SHOW_LANGUAGE: "True"
          SHOW_COMMIT: "True"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_SHORT_INFO: "False"
          SHOW_LINES_OF_CODE: "True"
